
/**
* ContaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conta.idl
* Terça-feira, 27 de Setembro de 2016 18h10min32s BRT
*/

public abstract class ContaPOA extends org.omg.PortableServer.Servant
 implements ContaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposito", new java.lang.Integer (0));
    _methods.put ("saque", new java.lang.Integer (1));
    _methods.put ("saldo", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Conta/deposito
       {
         float valor = in.read_float ();
         this.deposito (valor);
         out = $rh.createReply();
         break;
       }

       case 1:  // Conta/saque
       {
         float valor = in.read_float ();
         this.saque (valor);
         out = $rh.createReply();
         break;
       }

       case 2:  // Conta/saldo
       {
         float $result = (float)0;
         $result = this.saldo ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Conta:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Conta _this() 
  {
    return ContaHelper.narrow(
    super._this_object());
  }

  public Conta _this(org.omg.CORBA.ORB orb) 
  {
    return ContaHelper.narrow(
    super._this_object(orb));
  }


} // class ContaPOA
