
/**
* Conta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conta.idl
* Terça-feira, 27 de Setembro de 2016 18h10min32s BRT
*/

public interface Conta extends ContaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conta
