
/**
* ContaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conta.idl
* Terça-feira, 27 de Setembro de 2016 18h10min32s BRT
*/

public interface ContaOperations 
{
  void deposito (float valor);
  void saque (float valor);
  float saldo ();
} // interface ContaOperations
