
/**
* ContaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conta.idl
* Terça-feira, 27 de Setembro de 2016 18h10min32s BRT
*/

public final class ContaHolder implements org.omg.CORBA.portable.Streamable
{
  public Conta value = null;

  public ContaHolder ()
  {
  }

  public ContaHolder (Conta initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ContaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ContaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ContaHelper.type ();
  }

}
